Repository gvwilson/mossball, pull requests merged in 2025-01, with the labels that each got.

#8 Created grading scheme for Jan-Apr 2025
  GRADING.md
Labels: in-docs, pr-feature

#7 Create a minimal plugin - Cassandra
  cassandratin13/cassandra_demo.py
  cassandratin13/index.css
  cassandratin13/index.js
Labels: in-code, pr-feature

#9 Issue/5 - Evence
  evence_wang/SimpleWidget/.gitignore
  evence_wang/SimpleWidget/example.ipynb
  evence_wang/SimpleWidget/js/widget.css
  evence_wang/SimpleWidget/js/widget.tsx
  evence_wang/SimpleWidget/package-lock.json
  evence_wang/SimpleWidget/package.json
  evence_wang/SimpleWidget/pyproject.toml
  evence_wang/SimpleWidget/src/simple_widget/__init__.py
  evence_wang/SimpleWidget/tsconfig.json
  evence_wang/evence_demo.py
Labels: in-code, pr-feature

#12 Create a minimal plugin - David
  Barsamyan-D/README.md
  Barsamyan-D/demo_notebook.py
  Barsamyan-D/index.css
  Barsamyan-D/index.js
  Barsamyan-D/requirements.txt
Labels: in-code, pr-feature

#14 Issue #13 Review possible plugins
  README.md
Labels: pr-feature
