Repository gvwilson/mossball, pull requests merged in 2025-03, with the labels that each got.

#38 Frontend - global styling for widgets
  Barsamyan-D/str-strip-plugin-david/StructureStripWidget.py
  Barsamyan-D/str-strip-plugin-david/str.css
  Barsamyan-D/str-strip-plugin-david/str.js
  Barsamyan-D/str-strip-plugin-david/structure_strip.py
  cassandratin13/sort_paragraphs_plugin/SortTheParagraphs.py
  cassandratin13/sort_paragraphs_plugin/sort_paragraphs.py
  cassandratin13/sort_paragraphs_plugin/stp.css
  cassandratin13/sort_paragraphs_plugin/stp.js
  design-system/README.md
  design-system/global-svg-icons.js
  design-system/global.css
  eun-chae-s/drag-the-words/implementation/DragWordsWidget.py
  eun-chae-s/drag-the-words/implementation/drag_the_words.css
  eun-chae-s/drag-the-words/implementation/drag_the_words.js
  eun-chae-s/drag-the-words/implementation/drag_the_words.py
  evence_wang/FileUploaderModule/FileUploader.py
  evence_wang/FileUploaderModule/upload.css
  evence_wang/FileUploaderModule/upload.js
  lorena-b/find-the-words/demo.py
  lorena-b/find-the-words/js/constants.js
  lorena-b/find-the-words/js/icons.js
  lorena-b/find-the-words/js/utils.js
  lorena-b/find-the-words/js/widget.css
  lorena-b/find-the-words/js/widget.js
  lorena-b/find-the-words/src/find_the_words/__init__.py
Labels: in-code, issue-feature

#37 Backend work
  backends/institution/consts.py
  backends/institution/institution_backend.py
  backends/plugin/plugin_backend.py
  cassandratin13/sort_paragraphs_plugin/sessions/login.py
  cassandratin13/sort_paragraphs_plugin/sessions/session_manager.py
  cassandratin13/sort_paragraphs_plugin/sort_paragraphs.py
  cassandratin13/sort_paragraphs_plugin/stp.css
  cassandratin13/sort_paragraphs_plugin/stp.js
  cassandratin13/sort_paragraphs_plugin/widgets.py
Labels: in-code, pr-feature

#42 Add mcq styling
  cassandratin13/mcq_plugin/MCQPlugin.py
  cassandratin13/mcq_plugin/mcq.css
  cassandratin13/mcq_plugin/mcq.js
  cassandratin13/mcq_plugin/mcq_plugin.py
  cassandratin13/sort_paragraphs_plugin/stp.css
Labels: in-code, issue-feature

#45 Update GRADING.md
  GRADING.md
Labels: in-docs, pr-feature

#48 Add the backend logic for the widgets
  Barsamyan-D/str-strip-plugin-david/str.js
  backends/institution/consts.py
  backends/institution/dummy_data.py
  backends/institution/institution_backend.py
  backends/plugin/plugin_backend.py
  cassandratin13/mcq_plugin/mcq.js
  cassandratin13/sort_paragraphs_plugin/stp.js
  cassandratin13/sort_paragraphs_plugin/widgets.py
  eun-chae-s/drag-the-words/implementation/drag_the_words.css
  eun-chae-s/drag-the-words/implementation/drag_the_words.js
  frontend/sessions/__init__.py
  frontend/sessions/login.py
  frontend/sessions/session_manager.py
  frontend/widgets.py
  frontend/widgets_notebook.py
Labels: in-code, pr-feature

#52 Frontend with Backend integration
  eun-chae-s/drag-the-words/implementation/drag_the_words.js
  evence_wang/FileUploaderModule/upload.css
  frontend/widgets_notebook.py
  lorena-b/find-the-words/js/grid.js
Labels: in-code, pr-feature

#64 Local question support
  Barsamyan-D/str-strip-plugin-david/str.js
  backends/institution/institution_backend.py
  cassandratin13/mcq_plugin/mcq.js
  cassandratin13/sort_paragraphs_plugin/stp.js
  frontend/data.json
  frontend/widgets.py
  frontend/widgets_notebook.py
  frontend/widgets_notebook_local.py
Labels: in-code, pr-feature
