Repository gvwilson/mossball, pull requests merged in 2025-04, with the labels that each got.

#92 Change back to regular colour theme for demo
  frontend/widgets_notebook_local.py
Labels: in-code

#90 Add backend setup instructions in CONTRIBUTING.md
  CONTRIBUTING.md
  backends/backend-diagram.png
  backends/institution/institution_backend.py
  backends/plugin/plugin_backend.py
  tests/testfiles/test_backend.py
Labels: in-docs, pr-feature

#102 Adding multiple choice and sort the paragraphs to CONTRIBUTING.md
  CONTRIBUTING.md
  cassandratin13/mcq_plugin/README.md
  cassandratin13/mcq_plugin/mcq.js
  cassandratin13/mcq_plugin/mcq_plugin.py
  cassandratin13/sort_paragraphs_plugin/README.md
  cassandratin13/sort_paragraphs_plugin/sort_paragraphs.py
  cassandratin13/sort_paragraphs_plugin/sort_the_paragraphs_design.jpg
  cassandratin13/sort_paragraphs_plugin/sort_the_paragraphs_design_old.PNG
  cassandratin13/sort_paragraphs_plugin/stp.js
  frontend/widgets_notebook.py
Labels: in-docs, pr-feature

#100 Add styling contributing documentation
  CONTRIBUTING.md
Labels: in-docs

#103 Contributing structure strip
  Barsamyan-D/README.md
  Barsamyan-D/str-strip-plugin-david/README.md
  Barsamyan-D/str-strip-plugin-david/structure_strip.py
  CONTRIBUTING.md
Labels: in-docs, pr-feature
